#include "bind_parser.h" 
#include <stdio.h>

static const char* header = "// Autogenerated with bind_generator\n\n#include <Arika/Arika.h>\n#include <assert.h>\n\nextern ARFuncs* g_arFuncs;\n\n";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

int generate_exp(const char* filename, const BGFunction* func)
{
	FILE* f = fopen(filename, "wt");

	if (!f)
	{
		printf("Unable to open %s for write!", filename);
		return 0;
	}

	fprintf(f, "%s", header);

	while (func)
	{
		fprintf(f, "///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\n\n");
		fprintf(f, "%s ar_%s(", func->returnType, func->name);

		// write declaration

		for (int i = 0; i < func->parameterCount; ++i)
		{
			const BGParameter* param = &func->parameters[i];

			if (i == func->parameterCount - 1)	// handle the end of args where we shouldn't have a ,
				fprintf(f, "%s %s", param->type, param->variable);
			else
				fprintf(f, "%s %s, ", param->type, param->variable);
		}

		fprintf(f, ")\n");

		// write implementation

		fprintf(f, "{\n\tassert(g_arFuncs);\n");
		fprintf(f, "\treturn g_arFuncs->%s(", func->name);

		for (int i = 0; i < func->parameterCount; ++i)
		{
			const BGParameter* param = &func->parameters[i];

			if (i == func->parameterCount - 1)	// handle the end of args where we shouldn't have a ,
				fprintf(f, "%s", param->variable);
			else
				fprintf(f, "%s, ", param->variable);
		}

		fprintf(f, ");\n}\n\n", func->name);

		func = func->next;
	}

	fclose(f);

	return 1;
}

